version: '3'

volumes:
    db-data:

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  client-builder:
    user: ${UID}:${GID}
    build:
      context: .
      dockerfile: client-builder.Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db

  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
        - .:/app
    ports:
        - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
      - client-builder

